replicaCount: 1
image:
  repository: your-docker-repo/backend
  tag: latest
service:
  type: ClusterIP
  port: 3000
db:
  password: "your-db-password"
  name: "your-db-name"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
