name: Deploy Backend to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 476356830795.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and push backend Docker image
        run: |
          docker build -t 476356830795.dkr.ecr.ap-south-1.amazonaws.com/flask-backend:$GITHUB_SHA .
          docker push 476356830795.dkr.ecr.ap-south-1.amazonaws.com/flask-backend:$GITHUB_SHA

      - name: Deploy backend to Kubernetes using Helm
        run: |
          helm upgrade --install backend ./charts/backend
